services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Sincroniza sua pasta local com o container (Hot Reload)
    environment:
      - SECRET_KEY=b!kj$8&y#$gy64hm5he!ivj(fa&vpxd=6_pyas(_f#x6684w&%
      - DEBUG=True
    # Se vocÃª usar banco Postgres no futuro, adicionaria aqui